spring.application.name=frontend-service
server.port=8082

gateway.base-url=${GATEWAY_BASE_URL:http://localhost:8081}
gateway.security.username=${GATEWAY_USERNAME}
gateway.security.password=${GATEWAY_PASSWORD}